// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class _OFNOTIFYW {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            C_POINTER.withName("hwndFrom"),
            C_LONG_LONG.withName("idFrom"),
            C_INT.withName("code"),
            MemoryLayout.paddingLayout(32)
        ).withName("hdr"),
        C_POINTER.withName("lpOFN"),
        C_POINTER.withName("pszFile")
    ).withName("_OFNOTIFYW");
    public static MemoryLayout $LAYOUT() {
        return _OFNOTIFYW.$struct$LAYOUT;
    }
    public static MemorySegment hdr$slice(MemorySegment seg) {
        return seg.asSlice(0, 24);
    }
    static final VarHandle lpOFN$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("lpOFN")));
    public static VarHandle lpOFN$VH() {
        return _OFNOTIFYW.lpOFN$VH;
    }
    public static MemoryAddress lpOFN$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)_OFNOTIFYW.lpOFN$VH.get(seg);
    }
    public static void lpOFN$set( MemorySegment seg, MemoryAddress x) {
        _OFNOTIFYW.lpOFN$VH.set(seg, x);
    }
    public static MemoryAddress lpOFN$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)_OFNOTIFYW.lpOFN$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lpOFN$set(MemorySegment seg, long index, MemoryAddress x) {
        _OFNOTIFYW.lpOFN$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle pszFile$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("pszFile")));
    public static VarHandle pszFile$VH() {
        return _OFNOTIFYW.pszFile$VH;
    }
    public static MemoryAddress pszFile$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)_OFNOTIFYW.pszFile$VH.get(seg);
    }
    public static void pszFile$set( MemorySegment seg, MemoryAddress x) {
        _OFNOTIFYW.pszFile$VH.set(seg, x);
    }
    public static MemoryAddress pszFile$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)_OFNOTIFYW.pszFile$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void pszFile$set(MemorySegment seg, long index, MemoryAddress x) {
        _OFNOTIFYW.pszFile$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


