// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class AsyncIUnknownVtbl {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("Begin_QueryInterface"),
        C_POINTER.withName("Finish_QueryInterface"),
        C_POINTER.withName("Begin_AddRef"),
        C_POINTER.withName("Finish_AddRef"),
        C_POINTER.withName("Begin_Release"),
        C_POINTER.withName("Finish_Release")
    ).withName("AsyncIUnknownVtbl");
    public static MemoryLayout $LAYOUT() {
        return AsyncIUnknownVtbl.$struct$LAYOUT;
    }
    static final FunctionDescriptor QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.QueryInterface$FUNC, false
    );
    public interface QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2);
        static MemoryAddress allocate(QueryInterface fi) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, AsyncIUnknownVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, AsyncIUnknownVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2) -> {
                try {
                    return (int)AsyncIUnknownVtbl.QueryInterface$MH.invokeExact((Addressable)addr, x0, x1, x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    public static VarHandle QueryInterface$VH() {
        return AsyncIUnknownVtbl.QueryInterface$VH;
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.QueryInterface$VH.get(seg);
    }
    public static void QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static QueryInterface QueryInterface (MemorySegment segment) {
        return QueryInterface.ofAddress(QueryInterface$get(segment));
    }
    static final FunctionDescriptor AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.AddRef$FUNC, false
    );
    public interface AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(AddRef fi) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, AsyncIUnknownVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, AsyncIUnknownVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    public static VarHandle AddRef$VH() {
        return AsyncIUnknownVtbl.AddRef$VH;
    }
    public static MemoryAddress AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.AddRef$VH.get(seg);
    }
    public static void AddRef$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.AddRef$VH.set(seg, x);
    }
    public static MemoryAddress AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static AddRef AddRef (MemorySegment segment) {
        return AddRef.ofAddress(AddRef$get(segment));
    }
    static final FunctionDescriptor Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Release$FUNC, false
    );
    public interface Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Release fi) {
            return RuntimeHelper.upcallStub(Release.class, fi, AsyncIUnknownVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Release.class, fi, AsyncIUnknownVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    public static VarHandle Release$VH() {
        return AsyncIUnknownVtbl.Release$VH;
    }
    public static MemoryAddress Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Release$VH.get(seg);
    }
    public static void Release$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Release$VH.set(seg, x);
    }
    public static MemoryAddress Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Release$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Release Release (MemorySegment segment) {
        return Release.ofAddress(Release$get(segment));
    }
    static final FunctionDescriptor Begin_QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle Begin_QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Begin_QueryInterface$FUNC, false
    );
    public interface Begin_QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1);
        static MemoryAddress allocate(Begin_QueryInterface fi) {
            return RuntimeHelper.upcallStub(Begin_QueryInterface.class, fi, AsyncIUnknownVtbl.Begin_QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Begin_QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Begin_QueryInterface.class, fi, AsyncIUnknownVtbl.Begin_QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Begin_QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Begin_QueryInterface$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Begin_QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Begin_QueryInterface")));
    public static VarHandle Begin_QueryInterface$VH() {
        return AsyncIUnknownVtbl.Begin_QueryInterface$VH;
    }
    public static MemoryAddress Begin_QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_QueryInterface$VH.get(seg);
    }
    public static void Begin_QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress Begin_QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Begin_QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Begin_QueryInterface Begin_QueryInterface (MemorySegment segment) {
        return Begin_QueryInterface.ofAddress(Begin_QueryInterface$get(segment));
    }
    static final FunctionDescriptor Finish_QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle Finish_QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Finish_QueryInterface$FUNC, false
    );
    public interface Finish_QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1);
        static MemoryAddress allocate(Finish_QueryInterface fi) {
            return RuntimeHelper.upcallStub(Finish_QueryInterface.class, fi, AsyncIUnknownVtbl.Finish_QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Finish_QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Finish_QueryInterface.class, fi, AsyncIUnknownVtbl.Finish_QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Finish_QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Finish_QueryInterface$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Finish_QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Finish_QueryInterface")));
    public static VarHandle Finish_QueryInterface$VH() {
        return AsyncIUnknownVtbl.Finish_QueryInterface$VH;
    }
    public static MemoryAddress Finish_QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_QueryInterface$VH.get(seg);
    }
    public static void Finish_QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress Finish_QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Finish_QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Finish_QueryInterface Finish_QueryInterface (MemorySegment segment) {
        return Finish_QueryInterface.ofAddress(Finish_QueryInterface$get(segment));
    }
    static final FunctionDescriptor Begin_AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Begin_AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Begin_AddRef$FUNC, false
    );
    public interface Begin_AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Begin_AddRef fi) {
            return RuntimeHelper.upcallStub(Begin_AddRef.class, fi, AsyncIUnknownVtbl.Begin_AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Begin_AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Begin_AddRef.class, fi, AsyncIUnknownVtbl.Begin_AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Begin_AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Begin_AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Begin_AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Begin_AddRef")));
    public static VarHandle Begin_AddRef$VH() {
        return AsyncIUnknownVtbl.Begin_AddRef$VH;
    }
    public static MemoryAddress Begin_AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_AddRef$VH.get(seg);
    }
    public static void Begin_AddRef$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_AddRef$VH.set(seg, x);
    }
    public static MemoryAddress Begin_AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Begin_AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Begin_AddRef Begin_AddRef (MemorySegment segment) {
        return Begin_AddRef.ofAddress(Begin_AddRef$get(segment));
    }
    static final FunctionDescriptor Finish_AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Finish_AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Finish_AddRef$FUNC, false
    );
    public interface Finish_AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Finish_AddRef fi) {
            return RuntimeHelper.upcallStub(Finish_AddRef.class, fi, AsyncIUnknownVtbl.Finish_AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Finish_AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Finish_AddRef.class, fi, AsyncIUnknownVtbl.Finish_AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Finish_AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Finish_AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Finish_AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Finish_AddRef")));
    public static VarHandle Finish_AddRef$VH() {
        return AsyncIUnknownVtbl.Finish_AddRef$VH;
    }
    public static MemoryAddress Finish_AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_AddRef$VH.get(seg);
    }
    public static void Finish_AddRef$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_AddRef$VH.set(seg, x);
    }
    public static MemoryAddress Finish_AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Finish_AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Finish_AddRef Finish_AddRef (MemorySegment segment) {
        return Finish_AddRef.ofAddress(Finish_AddRef$get(segment));
    }
    static final FunctionDescriptor Begin_Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Begin_Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Begin_Release$FUNC, false
    );
    public interface Begin_Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Begin_Release fi) {
            return RuntimeHelper.upcallStub(Begin_Release.class, fi, AsyncIUnknownVtbl.Begin_Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Begin_Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Begin_Release.class, fi, AsyncIUnknownVtbl.Begin_Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Begin_Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Begin_Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Begin_Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Begin_Release")));
    public static VarHandle Begin_Release$VH() {
        return AsyncIUnknownVtbl.Begin_Release$VH;
    }
    public static MemoryAddress Begin_Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_Release$VH.get(seg);
    }
    public static void Begin_Release$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_Release$VH.set(seg, x);
    }
    public static MemoryAddress Begin_Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Begin_Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Begin_Release$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Begin_Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Begin_Release Begin_Release (MemorySegment segment) {
        return Begin_Release.ofAddress(Begin_Release$get(segment));
    }
    static final FunctionDescriptor Finish_Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Finish_Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        AsyncIUnknownVtbl.Finish_Release$FUNC, false
    );
    public interface Finish_Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Finish_Release fi) {
            return RuntimeHelper.upcallStub(Finish_Release.class, fi, AsyncIUnknownVtbl.Finish_Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Finish_Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Finish_Release.class, fi, AsyncIUnknownVtbl.Finish_Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Finish_Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)AsyncIUnknownVtbl.Finish_Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Finish_Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Finish_Release")));
    public static VarHandle Finish_Release$VH() {
        return AsyncIUnknownVtbl.Finish_Release$VH;
    }
    public static MemoryAddress Finish_Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_Release$VH.get(seg);
    }
    public static void Finish_Release$set( MemorySegment seg, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_Release$VH.set(seg, x);
    }
    public static MemoryAddress Finish_Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)AsyncIUnknownVtbl.Finish_Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Finish_Release$set(MemorySegment seg, long index, MemoryAddress x) {
        AsyncIUnknownVtbl.Finish_Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Finish_Release Finish_Release (MemorySegment segment) {
        return Finish_Release.ofAddress(Finish_Release$get(segment));
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


