// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$446 {

    static final FunctionDescriptor BackupEventLogA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle BackupEventLogA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "BackupEventLogA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.BackupEventLogA$FUNC, false
    );
    static final FunctionDescriptor BackupEventLogW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle BackupEventLogW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "BackupEventLogW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.BackupEventLogW$FUNC, false
    );
    static final FunctionDescriptor CloseEventLog$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle CloseEventLog$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CloseEventLog",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.CloseEventLog$FUNC, false
    );
    static final FunctionDescriptor DeregisterEventSource$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle DeregisterEventSource$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "DeregisterEventSource",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.DeregisterEventSource$FUNC, false
    );
    static final FunctionDescriptor NotifyChangeEventLog$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle NotifyChangeEventLog$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "NotifyChangeEventLog",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.NotifyChangeEventLog$FUNC, false
    );
    static final FunctionDescriptor GetNumberOfEventLogRecords$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle GetNumberOfEventLogRecords$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "GetNumberOfEventLogRecords",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$446.GetNumberOfEventLogRecords$FUNC, false
    );
}


