// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1234 {

    static final FunctionDescriptor VarBoolFromI1$FUNC = FunctionDescriptor.of(C_LONG,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle VarBoolFromI1$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarBoolFromI1",
        "(BLjdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarBoolFromI1$FUNC, false
    );
    static final FunctionDescriptor VarBoolFromUI2$FUNC = FunctionDescriptor.of(C_LONG,
        C_SHORT,
        C_POINTER
    );
    static final MethodHandle VarBoolFromUI2$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarBoolFromUI2",
        "(SLjdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarBoolFromUI2$FUNC, false
    );
    static final FunctionDescriptor VarBoolFromUI4$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle VarBoolFromUI4$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarBoolFromUI4",
        "(ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarBoolFromUI4$FUNC, false
    );
    static final FunctionDescriptor VarBoolFromUI8$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle VarBoolFromUI8$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarBoolFromUI8",
        "(JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarBoolFromUI8$FUNC, false
    );
    static final FunctionDescriptor VarBoolFromDec$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle VarBoolFromDec$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarBoolFromDec",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarBoolFromDec$FUNC, false
    );
    static final FunctionDescriptor VarI1FromUI1$FUNC = FunctionDescriptor.of(C_LONG,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle VarI1FromUI1$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VarI1FromUI1",
        "(BLjdk/incubator/foreign/MemoryAddress;)I",
        constants$1234.VarI1FromUI1$FUNC, false
    );
}


