// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$101 {

    static final FunctionDescriptor _execvp$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _execvp$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_execvp",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$101._execvp$FUNC, false
    );
    static final FunctionDescriptor _execvpe$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _execvpe$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_execvpe",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$101._execvpe$FUNC, false
    );
    static final FunctionDescriptor _spawnl$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _spawnl$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_spawnl",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)J",
        constants$101._spawnl$FUNC, true
    );
    static final FunctionDescriptor _spawnle$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _spawnle$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_spawnle",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)J",
        constants$101._spawnle$FUNC, true
    );
    static final FunctionDescriptor _spawnlp$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _spawnlp$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_spawnlp",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)J",
        constants$101._spawnlp$FUNC, true
    );
    static final FunctionDescriptor _spawnlpe$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _spawnlpe$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_spawnlpe",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)J",
        constants$101._spawnlpe$FUNC, true
    );
}


