// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$758 {

    static final FunctionDescriptor midiOutReset$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle midiOutReset$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiOutReset",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$758.midiOutReset$FUNC, false
    );
    static final FunctionDescriptor midiOutCachePatches$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle midiOutCachePatches$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiOutCachePatches",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$758.midiOutCachePatches$FUNC, false
    );
    static final FunctionDescriptor midiOutCacheDrumPatches$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle midiOutCacheDrumPatches$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiOutCacheDrumPatches",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$758.midiOutCacheDrumPatches$FUNC, false
    );
    static final FunctionDescriptor midiOutGetID$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle midiOutGetID$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiOutGetID",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$758.midiOutGetID$FUNC, false
    );
    static final FunctionDescriptor midiOutMessage$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle midiOutMessage$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiOutMessage",
        "(Ljdk/incubator/foreign/MemoryAddress;IJJ)I",
        constants$758.midiOutMessage$FUNC, false
    );
    static final FunctionDescriptor midiInGetNumDevs$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle midiInGetNumDevs$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "midiInGetNumDevs",
        "()I",
        constants$758.midiInGetNumDevs$FUNC, false
    );
}


