// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1170 {

    static final FunctionDescriptor CreateAsyncBindCtxEx$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle CreateAsyncBindCtxEx$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CreateAsyncBindCtxEx",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$1170.CreateAsyncBindCtxEx$FUNC, false
    );
    static final FunctionDescriptor MkParseDisplayNameEx$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle MkParseDisplayNameEx$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "MkParseDisplayNameEx",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1170.MkParseDisplayNameEx$FUNC, false
    );
    static final FunctionDescriptor RegisterBindStatusCallback$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle RegisterBindStatusCallback$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegisterBindStatusCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$1170.RegisterBindStatusCallback$FUNC, false
    );
    static final FunctionDescriptor RevokeBindStatusCallback$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RevokeBindStatusCallback$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RevokeBindStatusCallback",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1170.RevokeBindStatusCallback$FUNC, false
    );
    static final FunctionDescriptor GetClassFileOrMime$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle GetClassFileOrMime$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "GetClassFileOrMime",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1170.GetClassFileOrMime$FUNC, false
    );
    static final FunctionDescriptor IsValidURL$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle IsValidURL$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IsValidURL",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$1170.IsValidURL$FUNC, false
    );
}


