// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1461 {

    static final MemorySegment SZDDESYS_ITEM_HELP$SEGMENT = CLinker.toCString("Help", ResourceScope.newImplicitScope());
    static final MemorySegment SZDDE_ITEM_ITEMLIST$SEGMENT = CLinker.toCString("TopicItemList", ResourceScope.newImplicitScope());
    static final MemoryAddress CBR_BLOCK$ADDR = MemoryAddress.ofLong(-1L);
    static final MemorySegment ALL_TRANSPORTS$SEGMENT = CLinker.toCString("M", ResourceScope.newImplicitScope());
    static final MemorySegment MS_NBF$SEGMENT = CLinker.toCString("MNBF", ResourceScope.newImplicitScope());
    static final MemoryAddress RPC_C_NO_CREDENTIALS$ADDR = MemoryAddress.ofLong(-1L);
}


