// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1501 {

    static final MemorySegment szOID_RSA_envelopedData$SEGMENT = CLinker.toCString("1.2.840.113549.1.7.3", ResourceScope.newImplicitScope());
    static final MemorySegment szOID_RSA_signEnvData$SEGMENT = CLinker.toCString("1.2.840.113549.1.7.4", ResourceScope.newImplicitScope());
    static final MemorySegment szOID_RSA_digestedData$SEGMENT = CLinker.toCString("1.2.840.113549.1.7.5", ResourceScope.newImplicitScope());
    static final MemorySegment szOID_RSA_hashedData$SEGMENT = CLinker.toCString("1.2.840.113549.1.7.5", ResourceScope.newImplicitScope());
    static final MemorySegment szOID_RSA_encryptedData$SEGMENT = CLinker.toCString("1.2.840.113549.1.7.6", ResourceScope.newImplicitScope());
    static final MemorySegment szOID_RSA_emailAddr$SEGMENT = CLinker.toCString("1.2.840.113549.1.9.1", ResourceScope.newImplicitScope());
}


