// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1038 {

    static final FunctionDescriptor FLAG_STGMEDIUM_UserSize$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle FLAG_STGMEDIUM_UserSize$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FLAG_STGMEDIUM_UserSize",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1038.FLAG_STGMEDIUM_UserSize$FUNC, false
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserMarshal$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle FLAG_STGMEDIUM_UserMarshal$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FLAG_STGMEDIUM_UserMarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1038.FLAG_STGMEDIUM_UserMarshal$FUNC, false
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserUnmarshal$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle FLAG_STGMEDIUM_UserUnmarshal$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FLAG_STGMEDIUM_UserUnmarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1038.FLAG_STGMEDIUM_UserUnmarshal$FUNC, false
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserFree$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle FLAG_STGMEDIUM_UserFree$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FLAG_STGMEDIUM_UserFree",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1038.FLAG_STGMEDIUM_UserFree$FUNC, false
    );
    static final FunctionDescriptor HBITMAP_UserSize$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle HBITMAP_UserSize$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "HBITMAP_UserSize",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1038.HBITMAP_UserSize$FUNC, false
    );
    static final FunctionDescriptor HBITMAP_UserMarshal$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle HBITMAP_UserMarshal$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "HBITMAP_UserMarshal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1038.HBITMAP_UserMarshal$FUNC, false
    );
}


