// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$791 {

    static final FunctionDescriptor RpcBindingSetAuthInfoExW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle RpcBindingSetAuthInfoExW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcBindingSetAuthInfoExW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$791.RpcBindingSetAuthInfoExW$FUNC, false
    );
    static final FunctionDescriptor RpcBindingInqAuthInfoExA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle RpcBindingInqAuthInfoExA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcBindingInqAuthInfoExA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$791.RpcBindingInqAuthInfoExA$FUNC, false
    );
    static final FunctionDescriptor RpcBindingInqAuthInfoExW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle RpcBindingInqAuthInfoExW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcBindingInqAuthInfoExW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$791.RpcBindingInqAuthInfoExW$FUNC, false
    );
    static final FunctionDescriptor RPC_AUTH_KEY_RETRIEVAL_FN$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RPC_AUTH_KEY_RETRIEVAL_FN$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$791.RPC_AUTH_KEY_RETRIEVAL_FN$FUNC, false
    );
    static final FunctionDescriptor RpcServerRegisterAuthInfoA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcServerRegisterAuthInfoA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcServerRegisterAuthInfoA",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$791.RpcServerRegisterAuthInfoA$FUNC, false
    );
}


