// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$879 {

    static final FunctionDescriptor PFN_CERT_STORE_PROV_DELETE_CTL$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle PFN_CERT_STORE_PROV_DELETE_CTL$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$879.PFN_CERT_STORE_PROV_DELETE_CTL$FUNC, false
    );
    static final FunctionDescriptor PFN_CERT_STORE_PROV_SET_CTL_PROPERTY$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle PFN_CERT_STORE_PROV_SET_CTL_PROPERTY$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;)I",
        constants$879.PFN_CERT_STORE_PROV_SET_CTL_PROPERTY$FUNC, false
    );
    static final FunctionDescriptor PFN_CERT_STORE_PROV_CONTROL$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle PFN_CERT_STORE_PROV_CONTROL$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;)I",
        constants$879.PFN_CERT_STORE_PROV_CONTROL$FUNC, false
    );
}


