// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$232 {

    static final FunctionDescriptor _mm_cmpgt_epi32$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_cmpgt_epi32$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cmpgt_epi32",
        "(JJ)J",
        constants$232._mm_cmpgt_epi32$FUNC, false
    );
    static final FunctionDescriptor _mm_cmplt_epi8$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_cmplt_epi8$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cmplt_epi8",
        "(JJ)J",
        constants$232._mm_cmplt_epi8$FUNC, false
    );
    static final FunctionDescriptor _mm_cmplt_epi16$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_cmplt_epi16$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cmplt_epi16",
        "(JJ)J",
        constants$232._mm_cmplt_epi16$FUNC, false
    );
    static final FunctionDescriptor _mm_cmplt_epi32$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_cmplt_epi32$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cmplt_epi32",
        "(JJ)J",
        constants$232._mm_cmplt_epi32$FUNC, false
    );
    static final FunctionDescriptor _mm_cvtsi64_sd$FUNC = FunctionDescriptor.of(C_DOUBLE,
        C_DOUBLE,
        C_LONG_LONG
    );
    static final MethodHandle _mm_cvtsi64_sd$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cvtsi64_sd",
        "(DJ)D",
        constants$232._mm_cvtsi64_sd$FUNC, false
    );
    static final FunctionDescriptor _mm_cvtsd_si64$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_DOUBLE
    );
    static final MethodHandle _mm_cvtsd_si64$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_cvtsd_si64",
        "(D)J",
        constants$232._mm_cvtsd_si64$FUNC, false
    );
}


