// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$813 {

    static final FunctionDescriptor I_RpcRecordCalloutFailure$FUNC = FunctionDescriptor.ofVoid(
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle I_RpcRecordCalloutFailure$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "I_RpcRecordCalloutFailure",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$813.I_RpcRecordCalloutFailure$FUNC, false
    );
    static final FunctionDescriptor RpcNsBindingExportA$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcNsBindingExportA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcNsBindingExportA",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$813.RpcNsBindingExportA$FUNC, false
    );
    static final FunctionDescriptor RpcNsBindingUnexportA$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcNsBindingUnexportA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcNsBindingUnexportA",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$813.RpcNsBindingUnexportA$FUNC, false
    );
    static final FunctionDescriptor RpcNsBindingExportW$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcNsBindingExportW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcNsBindingExportW",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$813.RpcNsBindingExportW$FUNC, false
    );
    static final FunctionDescriptor RpcNsBindingUnexportW$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcNsBindingUnexportW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcNsBindingUnexportW",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$813.RpcNsBindingUnexportW$FUNC, false
    );
    static final FunctionDescriptor RpcNsBindingExportPnPA$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RpcNsBindingExportPnPA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RpcNsBindingExportPnPA",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$813.RpcNsBindingExportPnPA$FUNC, false
    );
}


