// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class IAddrTrackingControlVtbl {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("EnableCOMDynamicAddrTracking"),
        C_POINTER.withName("DisableCOMDynamicAddrTracking")
    ).withName("IAddrTrackingControlVtbl");
    public static MemoryLayout $LAYOUT() {
        return IAddrTrackingControlVtbl.$struct$LAYOUT;
    }
    static final FunctionDescriptor QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IAddrTrackingControlVtbl.QueryInterface$FUNC, false
    );
    public interface QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2);
        static MemoryAddress allocate(QueryInterface fi) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IAddrTrackingControlVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IAddrTrackingControlVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2) -> {
                try {
                    return (int)IAddrTrackingControlVtbl.QueryInterface$MH.invokeExact((Addressable)addr, x0, x1, x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    public static VarHandle QueryInterface$VH() {
        return IAddrTrackingControlVtbl.QueryInterface$VH;
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.QueryInterface$VH.get(seg);
    }
    public static void QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        IAddrTrackingControlVtbl.QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        IAddrTrackingControlVtbl.QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static QueryInterface QueryInterface (MemorySegment segment) {
        return QueryInterface.ofAddress(QueryInterface$get(segment));
    }
    static final FunctionDescriptor AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IAddrTrackingControlVtbl.AddRef$FUNC, false
    );
    public interface AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(AddRef fi) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IAddrTrackingControlVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IAddrTrackingControlVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IAddrTrackingControlVtbl.AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    public static VarHandle AddRef$VH() {
        return IAddrTrackingControlVtbl.AddRef$VH;
    }
    public static MemoryAddress AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.AddRef$VH.get(seg);
    }
    public static void AddRef$set( MemorySegment seg, MemoryAddress x) {
        IAddrTrackingControlVtbl.AddRef$VH.set(seg, x);
    }
    public static MemoryAddress AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        IAddrTrackingControlVtbl.AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static AddRef AddRef (MemorySegment segment) {
        return AddRef.ofAddress(AddRef$get(segment));
    }
    static final FunctionDescriptor Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IAddrTrackingControlVtbl.Release$FUNC, false
    );
    public interface Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Release fi) {
            return RuntimeHelper.upcallStub(Release.class, fi, IAddrTrackingControlVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Release.class, fi, IAddrTrackingControlVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IAddrTrackingControlVtbl.Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    public static VarHandle Release$VH() {
        return IAddrTrackingControlVtbl.Release$VH;
    }
    public static MemoryAddress Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.Release$VH.get(seg);
    }
    public static void Release$set( MemorySegment seg, MemoryAddress x) {
        IAddrTrackingControlVtbl.Release$VH.set(seg, x);
    }
    public static MemoryAddress Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Release$set(MemorySegment seg, long index, MemoryAddress x) {
        IAddrTrackingControlVtbl.Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Release Release (MemorySegment segment) {
        return Release.ofAddress(Release$get(segment));
    }
    static final FunctionDescriptor EnableCOMDynamicAddrTracking$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle EnableCOMDynamicAddrTracking$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$FUNC, false
    );
    public interface EnableCOMDynamicAddrTracking {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(EnableCOMDynamicAddrTracking fi) {
            return RuntimeHelper.upcallStub(EnableCOMDynamicAddrTracking.class, fi, IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(EnableCOMDynamicAddrTracking fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(EnableCOMDynamicAddrTracking.class, fi, IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static EnableCOMDynamicAddrTracking ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle EnableCOMDynamicAddrTracking$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("EnableCOMDynamicAddrTracking")));
    public static VarHandle EnableCOMDynamicAddrTracking$VH() {
        return IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$VH;
    }
    public static MemoryAddress EnableCOMDynamicAddrTracking$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$VH.get(seg);
    }
    public static void EnableCOMDynamicAddrTracking$set( MemorySegment seg, MemoryAddress x) {
        IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$VH.set(seg, x);
    }
    public static MemoryAddress EnableCOMDynamicAddrTracking$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void EnableCOMDynamicAddrTracking$set(MemorySegment seg, long index, MemoryAddress x) {
        IAddrTrackingControlVtbl.EnableCOMDynamicAddrTracking$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static EnableCOMDynamicAddrTracking EnableCOMDynamicAddrTracking (MemorySegment segment) {
        return EnableCOMDynamicAddrTracking.ofAddress(EnableCOMDynamicAddrTracking$get(segment));
    }
    static final FunctionDescriptor DisableCOMDynamicAddrTracking$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle DisableCOMDynamicAddrTracking$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$FUNC, false
    );
    public interface DisableCOMDynamicAddrTracking {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(DisableCOMDynamicAddrTracking fi) {
            return RuntimeHelper.upcallStub(DisableCOMDynamicAddrTracking.class, fi, IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(DisableCOMDynamicAddrTracking fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(DisableCOMDynamicAddrTracking.class, fi, IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static DisableCOMDynamicAddrTracking ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle DisableCOMDynamicAddrTracking$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("DisableCOMDynamicAddrTracking")));
    public static VarHandle DisableCOMDynamicAddrTracking$VH() {
        return IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$VH;
    }
    public static MemoryAddress DisableCOMDynamicAddrTracking$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$VH.get(seg);
    }
    public static void DisableCOMDynamicAddrTracking$set( MemorySegment seg, MemoryAddress x) {
        IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$VH.set(seg, x);
    }
    public static MemoryAddress DisableCOMDynamicAddrTracking$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void DisableCOMDynamicAddrTracking$set(MemorySegment seg, long index, MemoryAddress x) {
        IAddrTrackingControlVtbl.DisableCOMDynamicAddrTracking$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static DisableCOMDynamicAddrTracking DisableCOMDynamicAddrTracking (MemorySegment segment) {
        return DisableCOMDynamicAddrTracking.ofAddress(DisableCOMDynamicAddrTracking$get(segment));
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


