// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class IBindingVtbl {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("Abort"),
        C_POINTER.withName("Suspend"),
        C_POINTER.withName("Resume"),
        C_POINTER.withName("SetPriority"),
        C_POINTER.withName("GetPriority"),
        C_POINTER.withName("GetBindResult")
    ).withName("IBindingVtbl");
    public static MemoryLayout $LAYOUT() {
        return IBindingVtbl.$struct$LAYOUT;
    }
    static final FunctionDescriptor QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.QueryInterface$FUNC, false
    );
    public interface QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2);
        static MemoryAddress allocate(QueryInterface fi) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IBindingVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IBindingVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2) -> {
                try {
                    return (int)IBindingVtbl.QueryInterface$MH.invokeExact((Addressable)addr, x0, x1, x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    public static VarHandle QueryInterface$VH() {
        return IBindingVtbl.QueryInterface$VH;
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.QueryInterface$VH.get(seg);
    }
    public static void QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static QueryInterface QueryInterface (MemorySegment segment) {
        return QueryInterface.ofAddress(QueryInterface$get(segment));
    }
    static final FunctionDescriptor AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.AddRef$FUNC, false
    );
    public interface AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(AddRef fi) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IBindingVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IBindingVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IBindingVtbl.AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    public static VarHandle AddRef$VH() {
        return IBindingVtbl.AddRef$VH;
    }
    public static MemoryAddress AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.AddRef$VH.get(seg);
    }
    public static void AddRef$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.AddRef$VH.set(seg, x);
    }
    public static MemoryAddress AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static AddRef AddRef (MemorySegment segment) {
        return AddRef.ofAddress(AddRef$get(segment));
    }
    static final FunctionDescriptor Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.Release$FUNC, false
    );
    public interface Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Release fi) {
            return RuntimeHelper.upcallStub(Release.class, fi, IBindingVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Release.class, fi, IBindingVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IBindingVtbl.Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    public static VarHandle Release$VH() {
        return IBindingVtbl.Release$VH;
    }
    public static MemoryAddress Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Release$VH.get(seg);
    }
    public static void Release$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.Release$VH.set(seg, x);
    }
    public static MemoryAddress Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Release$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Release Release (MemorySegment segment) {
        return Release.ofAddress(Release$get(segment));
    }
    static final FunctionDescriptor Abort$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Abort$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.Abort$FUNC, false
    );
    public interface Abort {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Abort fi) {
            return RuntimeHelper.upcallStub(Abort.class, fi, IBindingVtbl.Abort$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Abort fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Abort.class, fi, IBindingVtbl.Abort$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Abort ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IBindingVtbl.Abort$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Abort$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Abort")));
    public static VarHandle Abort$VH() {
        return IBindingVtbl.Abort$VH;
    }
    public static MemoryAddress Abort$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Abort$VH.get(seg);
    }
    public static void Abort$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.Abort$VH.set(seg, x);
    }
    public static MemoryAddress Abort$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Abort$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Abort$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.Abort$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Abort Abort (MemorySegment segment) {
        return Abort.ofAddress(Abort$get(segment));
    }
    static final FunctionDescriptor Suspend$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Suspend$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.Suspend$FUNC, false
    );
    public interface Suspend {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Suspend fi) {
            return RuntimeHelper.upcallStub(Suspend.class, fi, IBindingVtbl.Suspend$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Suspend fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Suspend.class, fi, IBindingVtbl.Suspend$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Suspend ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IBindingVtbl.Suspend$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Suspend$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Suspend")));
    public static VarHandle Suspend$VH() {
        return IBindingVtbl.Suspend$VH;
    }
    public static MemoryAddress Suspend$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Suspend$VH.get(seg);
    }
    public static void Suspend$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.Suspend$VH.set(seg, x);
    }
    public static MemoryAddress Suspend$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Suspend$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Suspend$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.Suspend$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Suspend Suspend (MemorySegment segment) {
        return Suspend.ofAddress(Suspend$get(segment));
    }
    static final FunctionDescriptor Resume$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Resume$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.Resume$FUNC, false
    );
    public interface Resume {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Resume fi) {
            return RuntimeHelper.upcallStub(Resume.class, fi, IBindingVtbl.Resume$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Resume fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Resume.class, fi, IBindingVtbl.Resume$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Resume ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IBindingVtbl.Resume$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Resume$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Resume")));
    public static VarHandle Resume$VH() {
        return IBindingVtbl.Resume$VH;
    }
    public static MemoryAddress Resume$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Resume$VH.get(seg);
    }
    public static void Resume$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.Resume$VH.set(seg, x);
    }
    public static MemoryAddress Resume$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.Resume$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Resume$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.Resume$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Resume Resume (MemorySegment segment) {
        return Resume.ofAddress(Resume$get(segment));
    }
    static final FunctionDescriptor SetPriority$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle SetPriority$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        IBindingVtbl.SetPriority$FUNC, false
    );
    public interface SetPriority {

        int apply(jdk.incubator.foreign.MemoryAddress x0, int x1);
        static MemoryAddress allocate(SetPriority fi) {
            return RuntimeHelper.upcallStub(SetPriority.class, fi, IBindingVtbl.SetPriority$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;I)I");
        }
        static MemoryAddress allocate(SetPriority fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(SetPriority.class, fi, IBindingVtbl.SetPriority$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;I)I", scope);
        }
        static SetPriority ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, int x1) -> {
                try {
                    return (int)IBindingVtbl.SetPriority$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle SetPriority$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("SetPriority")));
    public static VarHandle SetPriority$VH() {
        return IBindingVtbl.SetPriority$VH;
    }
    public static MemoryAddress SetPriority$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.SetPriority$VH.get(seg);
    }
    public static void SetPriority$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.SetPriority$VH.set(seg, x);
    }
    public static MemoryAddress SetPriority$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.SetPriority$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void SetPriority$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.SetPriority$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static SetPriority SetPriority (MemorySegment segment) {
        return SetPriority.ofAddress(SetPriority$get(segment));
    }
    static final FunctionDescriptor GetPriority$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle GetPriority$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.GetPriority$FUNC, false
    );
    public interface GetPriority {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1);
        static MemoryAddress allocate(GetPriority fi) {
            return RuntimeHelper.upcallStub(GetPriority.class, fi, IBindingVtbl.GetPriority$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(GetPriority fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(GetPriority.class, fi, IBindingVtbl.GetPriority$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static GetPriority ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)IBindingVtbl.GetPriority$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle GetPriority$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetPriority")));
    public static VarHandle GetPriority$VH() {
        return IBindingVtbl.GetPriority$VH;
    }
    public static MemoryAddress GetPriority$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.GetPriority$VH.get(seg);
    }
    public static void GetPriority$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.GetPriority$VH.set(seg, x);
    }
    public static MemoryAddress GetPriority$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.GetPriority$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void GetPriority$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.GetPriority$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static GetPriority GetPriority (MemorySegment segment) {
        return GetPriority.ofAddress(GetPriority$get(segment));
    }
    static final FunctionDescriptor GetBindResult$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle GetBindResult$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IBindingVtbl.GetBindResult$FUNC, false
    );
    public interface GetBindResult {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3, jdk.incubator.foreign.MemoryAddress x4);
        static MemoryAddress allocate(GetBindResult fi) {
            return RuntimeHelper.upcallStub(GetBindResult.class, fi, IBindingVtbl.GetBindResult$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(GetBindResult fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(GetBindResult.class, fi, IBindingVtbl.GetBindResult$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static GetBindResult ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3, jdk.incubator.foreign.MemoryAddress x4) -> {
                try {
                    return (int)IBindingVtbl.GetBindResult$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle GetBindResult$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetBindResult")));
    public static VarHandle GetBindResult$VH() {
        return IBindingVtbl.GetBindResult$VH;
    }
    public static MemoryAddress GetBindResult$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.GetBindResult$VH.get(seg);
    }
    public static void GetBindResult$set( MemorySegment seg, MemoryAddress x) {
        IBindingVtbl.GetBindResult$VH.set(seg, x);
    }
    public static MemoryAddress GetBindResult$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IBindingVtbl.GetBindResult$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void GetBindResult$set(MemorySegment seg, long index, MemoryAddress x) {
        IBindingVtbl.GetBindResult$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static GetBindResult GetBindResult (MemorySegment segment) {
        return GetBindResult.ofAddress(GetBindResult$get(segment));
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


