// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class IMarshalVtbl {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_POINTER.withName("QueryInterface"),
        C_POINTER.withName("AddRef"),
        C_POINTER.withName("Release"),
        C_POINTER.withName("GetUnmarshalClass"),
        C_POINTER.withName("GetMarshalSizeMax"),
        C_POINTER.withName("MarshalInterface"),
        C_POINTER.withName("UnmarshalInterface"),
        C_POINTER.withName("ReleaseMarshalData"),
        C_POINTER.withName("DisconnectObject")
    ).withName("IMarshalVtbl");
    public static MemoryLayout $LAYOUT() {
        return IMarshalVtbl.$struct$LAYOUT;
    }
    static final FunctionDescriptor QueryInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle QueryInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.QueryInterface$FUNC, false
    );
    public interface QueryInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2);
        static MemoryAddress allocate(QueryInterface fi) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IMarshalVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(QueryInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(QueryInterface.class, fi, IMarshalVtbl.QueryInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static QueryInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2) -> {
                try {
                    return (int)IMarshalVtbl.QueryInterface$MH.invokeExact((Addressable)addr, x0, x1, x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle QueryInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("QueryInterface")));
    public static VarHandle QueryInterface$VH() {
        return IMarshalVtbl.QueryInterface$VH;
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.QueryInterface$VH.get(seg);
    }
    public static void QueryInterface$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.QueryInterface$VH.set(seg, x);
    }
    public static MemoryAddress QueryInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.QueryInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void QueryInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.QueryInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static QueryInterface QueryInterface (MemorySegment segment) {
        return QueryInterface.ofAddress(QueryInterface$get(segment));
    }
    static final FunctionDescriptor AddRef$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle AddRef$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.AddRef$FUNC, false
    );
    public interface AddRef {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(AddRef fi) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IMarshalVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(AddRef fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(AddRef.class, fi, IMarshalVtbl.AddRef$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static AddRef ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IMarshalVtbl.AddRef$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle AddRef$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("AddRef")));
    public static VarHandle AddRef$VH() {
        return IMarshalVtbl.AddRef$VH;
    }
    public static MemoryAddress AddRef$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.AddRef$VH.get(seg);
    }
    public static void AddRef$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.AddRef$VH.set(seg, x);
    }
    public static MemoryAddress AddRef$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.AddRef$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AddRef$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.AddRef$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static AddRef AddRef (MemorySegment segment) {
        return AddRef.ofAddress(AddRef$get(segment));
    }
    static final FunctionDescriptor Release$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle Release$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.Release$FUNC, false
    );
    public interface Release {

        int apply(jdk.incubator.foreign.MemoryAddress x0);
        static MemoryAddress allocate(Release fi) {
            return RuntimeHelper.upcallStub(Release.class, fi, IMarshalVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(Release fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(Release.class, fi, IMarshalVtbl.Release$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static Release ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (int)IMarshalVtbl.Release$MH.invokeExact((Addressable)addr, x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle Release$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("Release")));
    public static VarHandle Release$VH() {
        return IMarshalVtbl.Release$VH;
    }
    public static MemoryAddress Release$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.Release$VH.get(seg);
    }
    public static void Release$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.Release$VH.set(seg, x);
    }
    public static MemoryAddress Release$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.Release$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Release$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.Release$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static Release Release (MemorySegment segment) {
        return Release.ofAddress(Release$get(segment));
    }
    static final FunctionDescriptor GetUnmarshalClass$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle GetUnmarshalClass$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.GetUnmarshalClass$FUNC, false
    );
    public interface GetUnmarshalClass {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, int x3, jdk.incubator.foreign.MemoryAddress x4, int x5, jdk.incubator.foreign.MemoryAddress x6);
        static MemoryAddress allocate(GetUnmarshalClass fi) {
            return RuntimeHelper.upcallStub(GetUnmarshalClass.class, fi, IMarshalVtbl.GetUnmarshalClass$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(GetUnmarshalClass fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(GetUnmarshalClass.class, fi, IMarshalVtbl.GetUnmarshalClass$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static GetUnmarshalClass ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, int x3, jdk.incubator.foreign.MemoryAddress x4, int x5, jdk.incubator.foreign.MemoryAddress x6) -> {
                try {
                    return (int)IMarshalVtbl.GetUnmarshalClass$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5, x6);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle GetUnmarshalClass$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetUnmarshalClass")));
    public static VarHandle GetUnmarshalClass$VH() {
        return IMarshalVtbl.GetUnmarshalClass$VH;
    }
    public static MemoryAddress GetUnmarshalClass$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.GetUnmarshalClass$VH.get(seg);
    }
    public static void GetUnmarshalClass$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.GetUnmarshalClass$VH.set(seg, x);
    }
    public static MemoryAddress GetUnmarshalClass$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.GetUnmarshalClass$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void GetUnmarshalClass$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.GetUnmarshalClass$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static GetUnmarshalClass GetUnmarshalClass (MemorySegment segment) {
        return GetUnmarshalClass.ofAddress(GetUnmarshalClass$get(segment));
    }
    static final FunctionDescriptor GetMarshalSizeMax$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle GetMarshalSizeMax$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.GetMarshalSizeMax$FUNC, false
    );
    public interface GetMarshalSizeMax {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, int x3, jdk.incubator.foreign.MemoryAddress x4, int x5, jdk.incubator.foreign.MemoryAddress x6);
        static MemoryAddress allocate(GetMarshalSizeMax fi) {
            return RuntimeHelper.upcallStub(GetMarshalSizeMax.class, fi, IMarshalVtbl.GetMarshalSizeMax$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(GetMarshalSizeMax fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(GetMarshalSizeMax.class, fi, IMarshalVtbl.GetMarshalSizeMax$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static GetMarshalSizeMax ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, int x3, jdk.incubator.foreign.MemoryAddress x4, int x5, jdk.incubator.foreign.MemoryAddress x6) -> {
                try {
                    return (int)IMarshalVtbl.GetMarshalSizeMax$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5, x6);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle GetMarshalSizeMax$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("GetMarshalSizeMax")));
    public static VarHandle GetMarshalSizeMax$VH() {
        return IMarshalVtbl.GetMarshalSizeMax$VH;
    }
    public static MemoryAddress GetMarshalSizeMax$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.GetMarshalSizeMax$VH.get(seg);
    }
    public static void GetMarshalSizeMax$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.GetMarshalSizeMax$VH.set(seg, x);
    }
    public static MemoryAddress GetMarshalSizeMax$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.GetMarshalSizeMax$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void GetMarshalSizeMax$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.GetMarshalSizeMax$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static GetMarshalSizeMax GetMarshalSizeMax (MemorySegment segment) {
        return GetMarshalSizeMax.ofAddress(GetMarshalSizeMax$get(segment));
    }
    static final FunctionDescriptor MarshalInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle MarshalInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        IMarshalVtbl.MarshalInterface$FUNC, false
    );
    public interface MarshalInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3, int x4, jdk.incubator.foreign.MemoryAddress x5, int x6);
        static MemoryAddress allocate(MarshalInterface fi) {
            return RuntimeHelper.upcallStub(MarshalInterface.class, fi, IMarshalVtbl.MarshalInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I");
        }
        static MemoryAddress allocate(MarshalInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(MarshalInterface.class, fi, IMarshalVtbl.MarshalInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I", scope);
        }
        static MarshalInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3, int x4, jdk.incubator.foreign.MemoryAddress x5, int x6) -> {
                try {
                    return (int)IMarshalVtbl.MarshalInterface$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4, x5, x6);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle MarshalInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("MarshalInterface")));
    public static VarHandle MarshalInterface$VH() {
        return IMarshalVtbl.MarshalInterface$VH;
    }
    public static MemoryAddress MarshalInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.MarshalInterface$VH.get(seg);
    }
    public static void MarshalInterface$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.MarshalInterface$VH.set(seg, x);
    }
    public static MemoryAddress MarshalInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.MarshalInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void MarshalInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.MarshalInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MarshalInterface MarshalInterface (MemorySegment segment) {
        return MarshalInterface.ofAddress(MarshalInterface$get(segment));
    }
    static final FunctionDescriptor UnmarshalInterface$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle UnmarshalInterface$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.UnmarshalInterface$FUNC, false
    );
    public interface UnmarshalInterface {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3);
        static MemoryAddress allocate(UnmarshalInterface fi) {
            return RuntimeHelper.upcallStub(UnmarshalInterface.class, fi, IMarshalVtbl.UnmarshalInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(UnmarshalInterface fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(UnmarshalInterface.class, fi, IMarshalVtbl.UnmarshalInterface$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static UnmarshalInterface ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1, jdk.incubator.foreign.MemoryAddress x2, jdk.incubator.foreign.MemoryAddress x3) -> {
                try {
                    return (int)IMarshalVtbl.UnmarshalInterface$MH.invokeExact((Addressable)addr, x0, x1, x2, x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle UnmarshalInterface$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("UnmarshalInterface")));
    public static VarHandle UnmarshalInterface$VH() {
        return IMarshalVtbl.UnmarshalInterface$VH;
    }
    public static MemoryAddress UnmarshalInterface$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.UnmarshalInterface$VH.get(seg);
    }
    public static void UnmarshalInterface$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.UnmarshalInterface$VH.set(seg, x);
    }
    public static MemoryAddress UnmarshalInterface$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.UnmarshalInterface$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void UnmarshalInterface$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.UnmarshalInterface$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static UnmarshalInterface UnmarshalInterface (MemorySegment segment) {
        return UnmarshalInterface.ofAddress(UnmarshalInterface$get(segment));
    }
    static final FunctionDescriptor ReleaseMarshalData$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle ReleaseMarshalData$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        IMarshalVtbl.ReleaseMarshalData$FUNC, false
    );
    public interface ReleaseMarshalData {

        int apply(jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1);
        static MemoryAddress allocate(ReleaseMarshalData fi) {
            return RuntimeHelper.upcallStub(ReleaseMarshalData.class, fi, IMarshalVtbl.ReleaseMarshalData$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I");
        }
        static MemoryAddress allocate(ReleaseMarshalData fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(ReleaseMarshalData.class, fi, IMarshalVtbl.ReleaseMarshalData$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static ReleaseMarshalData ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)IMarshalVtbl.ReleaseMarshalData$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle ReleaseMarshalData$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("ReleaseMarshalData")));
    public static VarHandle ReleaseMarshalData$VH() {
        return IMarshalVtbl.ReleaseMarshalData$VH;
    }
    public static MemoryAddress ReleaseMarshalData$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.ReleaseMarshalData$VH.get(seg);
    }
    public static void ReleaseMarshalData$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.ReleaseMarshalData$VH.set(seg, x);
    }
    public static MemoryAddress ReleaseMarshalData$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.ReleaseMarshalData$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ReleaseMarshalData$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.ReleaseMarshalData$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static ReleaseMarshalData ReleaseMarshalData (MemorySegment segment) {
        return ReleaseMarshalData.ofAddress(ReleaseMarshalData$get(segment));
    }
    static final FunctionDescriptor DisconnectObject$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle DisconnectObject$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        IMarshalVtbl.DisconnectObject$FUNC, false
    );
    public interface DisconnectObject {

        int apply(jdk.incubator.foreign.MemoryAddress x0, int x1);
        static MemoryAddress allocate(DisconnectObject fi) {
            return RuntimeHelper.upcallStub(DisconnectObject.class, fi, IMarshalVtbl.DisconnectObject$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;I)I");
        }
        static MemoryAddress allocate(DisconnectObject fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(DisconnectObject.class, fi, IMarshalVtbl.DisconnectObject$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;I)I", scope);
        }
        static DisconnectObject ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, int x1) -> {
                try {
                    return (int)IMarshalVtbl.DisconnectObject$MH.invokeExact((Addressable)addr, x0, x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle DisconnectObject$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("DisconnectObject")));
    public static VarHandle DisconnectObject$VH() {
        return IMarshalVtbl.DisconnectObject$VH;
    }
    public static MemoryAddress DisconnectObject$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.DisconnectObject$VH.get(seg);
    }
    public static void DisconnectObject$set( MemorySegment seg, MemoryAddress x) {
        IMarshalVtbl.DisconnectObject$VH.set(seg, x);
    }
    public static MemoryAddress DisconnectObject$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)IMarshalVtbl.DisconnectObject$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void DisconnectObject$set(MemorySegment seg, long index, MemoryAddress x) {
        IMarshalVtbl.DisconnectObject$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static DisconnectObject DisconnectObject (MemorySegment segment) {
        return DisconnectObject.ofAddress(DisconnectObject$get(segment));
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


