// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class _DRIVE_LAYOUT_INFORMATION_EX {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("PartitionStyle"),
        C_LONG.withName("PartitionCount"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_LONG.withName("Signature")
            ).withName("Mbr"),
            MemoryLayout.structLayout(
                MemoryLayout.structLayout(
                    C_LONG.withName("Data1"),
                    C_SHORT.withName("Data2"),
                    C_SHORT.withName("Data3"),
                    MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
                ).withName("DiskId"),
                MemoryLayout.unionLayout(
                    MemoryLayout.structLayout(
                        C_LONG.withName("LowPart"),
                        C_LONG.withName("HighPart")
                    ).withName("$anon$0"),
                    MemoryLayout.structLayout(
                        C_LONG.withName("LowPart"),
                        C_LONG.withName("HighPart")
                    ).withName("u"),
                    C_LONG_LONG.withName("QuadPart")
                ).withName("StartingUsableOffset"),
                MemoryLayout.unionLayout(
                    MemoryLayout.structLayout(
                        C_LONG.withName("LowPart"),
                        C_LONG.withName("HighPart")
                    ).withName("$anon$0"),
                    MemoryLayout.structLayout(
                        C_LONG.withName("LowPart"),
                        C_LONG.withName("HighPart")
                    ).withName("u"),
                    C_LONG_LONG.withName("QuadPart")
                ).withName("UsableLength"),
                C_LONG.withName("MaxPartitionCount"),
                MemoryLayout.paddingLayout(32)
            ).withName("Gpt")
        ).withName("$anon$0"),
        MemoryLayout.sequenceLayout(1, MemoryLayout.structLayout(
            C_INT.withName("PartitionStyle"),
            MemoryLayout.paddingLayout(32),
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    C_LONG.withName("LowPart"),
                    C_LONG.withName("HighPart")
                ).withName("$anon$0"),
                MemoryLayout.structLayout(
                    C_LONG.withName("LowPart"),
                    C_LONG.withName("HighPart")
                ).withName("u"),
                C_LONG_LONG.withName("QuadPart")
            ).withName("StartingOffset"),
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    C_LONG.withName("LowPart"),
                    C_LONG.withName("HighPart")
                ).withName("$anon$0"),
                MemoryLayout.structLayout(
                    C_LONG.withName("LowPart"),
                    C_LONG.withName("HighPart")
                ).withName("u"),
                C_LONG_LONG.withName("QuadPart")
            ).withName("PartitionLength"),
            C_LONG.withName("PartitionNumber"),
            C_CHAR.withName("RewritePartition"),
            MemoryLayout.paddingLayout(24),
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    C_CHAR.withName("PartitionType"),
                    C_CHAR.withName("BootIndicator"),
                    C_CHAR.withName("RecognizedPartition"),
                    MemoryLayout.paddingLayout(8),
                    C_LONG.withName("HiddenSectors")
                ).withName("Mbr"),
                MemoryLayout.structLayout(
                    MemoryLayout.structLayout(
                        C_LONG.withName("Data1"),
                        C_SHORT.withName("Data2"),
                        C_SHORT.withName("Data3"),
                        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
                    ).withName("PartitionType"),
                    MemoryLayout.structLayout(
                        C_LONG.withName("Data1"),
                        C_SHORT.withName("Data2"),
                        C_SHORT.withName("Data3"),
                        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
                    ).withName("PartitionId"),
                    C_LONG_LONG.withName("Attributes"),
                    MemoryLayout.sequenceLayout(36, C_SHORT).withName("Name")
                ).withName("Gpt")
            ).withName("$anon$0")
        ).withName("_PARTITION_INFORMATION_EX")).withName("PartitionEntry")
    ).withName("_DRIVE_LAYOUT_INFORMATION_EX");
    public static MemoryLayout $LAYOUT() {
        return _DRIVE_LAYOUT_INFORMATION_EX.$struct$LAYOUT;
    }
    static final VarHandle PartitionStyle$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("PartitionStyle"));
    public static VarHandle PartitionStyle$VH() {
        return _DRIVE_LAYOUT_INFORMATION_EX.PartitionStyle$VH;
    }
    public static int PartitionStyle$get(MemorySegment seg) {
        return (int)_DRIVE_LAYOUT_INFORMATION_EX.PartitionStyle$VH.get(seg);
    }
    public static void PartitionStyle$set( MemorySegment seg, int x) {
        _DRIVE_LAYOUT_INFORMATION_EX.PartitionStyle$VH.set(seg, x);
    }
    public static int PartitionStyle$get(MemorySegment seg, long index) {
        return (int)_DRIVE_LAYOUT_INFORMATION_EX.PartitionStyle$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void PartitionStyle$set(MemorySegment seg, long index, int x) {
        _DRIVE_LAYOUT_INFORMATION_EX.PartitionStyle$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle PartitionCount$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("PartitionCount"));
    public static VarHandle PartitionCount$VH() {
        return _DRIVE_LAYOUT_INFORMATION_EX.PartitionCount$VH;
    }
    public static int PartitionCount$get(MemorySegment seg) {
        return (int)_DRIVE_LAYOUT_INFORMATION_EX.PartitionCount$VH.get(seg);
    }
    public static void PartitionCount$set( MemorySegment seg, int x) {
        _DRIVE_LAYOUT_INFORMATION_EX.PartitionCount$VH.set(seg, x);
    }
    public static int PartitionCount$get(MemorySegment seg, long index) {
        return (int)_DRIVE_LAYOUT_INFORMATION_EX.PartitionCount$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void PartitionCount$set(MemorySegment seg, long index, int x) {
        _DRIVE_LAYOUT_INFORMATION_EX.PartitionCount$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment Mbr$slice(MemorySegment seg) {
        return seg.asSlice(8, 4);
    }
    public static MemorySegment Gpt$slice(MemorySegment seg) {
        return seg.asSlice(8, 40);
    }
    public static MemorySegment PartitionEntry$slice(MemorySegment seg) {
        return seg.asSlice(48, 144);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


