// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class _TAPE_STATISTICS {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Version"),
        C_LONG.withName("Flags"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("u"),
            C_LONG_LONG.withName("QuadPart")
        ).withName("RecoveredWrites"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("u"),
            C_LONG_LONG.withName("QuadPart")
        ).withName("UnrecoveredWrites"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("u"),
            C_LONG_LONG.withName("QuadPart")
        ).withName("RecoveredReads"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                C_LONG.withName("LowPart"),
                C_LONG.withName("HighPart")
            ).withName("u"),
            C_LONG_LONG.withName("QuadPart")
        ).withName("UnrecoveredReads"),
        C_CHAR.withName("CompressionRatioReads"),
        C_CHAR.withName("CompressionRatioWrites"),
        MemoryLayout.paddingLayout(48)
    ).withName("_TAPE_STATISTICS");
    public static MemoryLayout $LAYOUT() {
        return _TAPE_STATISTICS.$struct$LAYOUT;
    }
    static final VarHandle Version$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("Version"));
    public static VarHandle Version$VH() {
        return _TAPE_STATISTICS.Version$VH;
    }
    public static int Version$get(MemorySegment seg) {
        return (int)_TAPE_STATISTICS.Version$VH.get(seg);
    }
    public static void Version$set( MemorySegment seg, int x) {
        _TAPE_STATISTICS.Version$VH.set(seg, x);
    }
    public static int Version$get(MemorySegment seg, long index) {
        return (int)_TAPE_STATISTICS.Version$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Version$set(MemorySegment seg, long index, int x) {
        _TAPE_STATISTICS.Version$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle Flags$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("Flags"));
    public static VarHandle Flags$VH() {
        return _TAPE_STATISTICS.Flags$VH;
    }
    public static int Flags$get(MemorySegment seg) {
        return (int)_TAPE_STATISTICS.Flags$VH.get(seg);
    }
    public static void Flags$set( MemorySegment seg, int x) {
        _TAPE_STATISTICS.Flags$VH.set(seg, x);
    }
    public static int Flags$get(MemorySegment seg, long index) {
        return (int)_TAPE_STATISTICS.Flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void Flags$set(MemorySegment seg, long index, int x) {
        _TAPE_STATISTICS.Flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment RecoveredWrites$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static MemorySegment UnrecoveredWrites$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment RecoveredReads$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static MemorySegment UnrecoveredReads$slice(MemorySegment seg) {
        return seg.asSlice(32, 8);
    }
    static final VarHandle CompressionRatioReads$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("CompressionRatioReads"));
    public static VarHandle CompressionRatioReads$VH() {
        return _TAPE_STATISTICS.CompressionRatioReads$VH;
    }
    public static byte CompressionRatioReads$get(MemorySegment seg) {
        return (byte)_TAPE_STATISTICS.CompressionRatioReads$VH.get(seg);
    }
    public static void CompressionRatioReads$set( MemorySegment seg, byte x) {
        _TAPE_STATISTICS.CompressionRatioReads$VH.set(seg, x);
    }
    public static byte CompressionRatioReads$get(MemorySegment seg, long index) {
        return (byte)_TAPE_STATISTICS.CompressionRatioReads$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void CompressionRatioReads$set(MemorySegment seg, long index, byte x) {
        _TAPE_STATISTICS.CompressionRatioReads$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle CompressionRatioWrites$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("CompressionRatioWrites"));
    public static VarHandle CompressionRatioWrites$VH() {
        return _TAPE_STATISTICS.CompressionRatioWrites$VH;
    }
    public static byte CompressionRatioWrites$get(MemorySegment seg) {
        return (byte)_TAPE_STATISTICS.CompressionRatioWrites$VH.get(seg);
    }
    public static void CompressionRatioWrites$set( MemorySegment seg, byte x) {
        _TAPE_STATISTICS.CompressionRatioWrites$VH.set(seg, x);
    }
    public static byte CompressionRatioWrites$get(MemorySegment seg, long index) {
        return (byte)_TAPE_STATISTICS.CompressionRatioWrites$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void CompressionRatioWrites$set(MemorySegment seg, long index, byte x) {
        _TAPE_STATISTICS.CompressionRatioWrites$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


