// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$561 {

    static final FunctionDescriptor GetMessageW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle GetMessageW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "GetMessageW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$561.GetMessageW$FUNC, false
    );
    static final FunctionDescriptor TranslateMessage$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle TranslateMessage$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "TranslateMessage",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$561.TranslateMessage$FUNC, false
    );
    static final FunctionDescriptor DispatchMessageA$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle DispatchMessageA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "DispatchMessageA",
        "(Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$561.DispatchMessageA$FUNC, false
    );
    static final FunctionDescriptor DispatchMessageW$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle DispatchMessageW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "DispatchMessageW",
        "(Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$561.DispatchMessageW$FUNC, false
    );
    static final FunctionDescriptor SetMessageQueue$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle SetMessageQueue$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "SetMessageQueue",
        "(I)I",
        constants$561.SetMessageQueue$FUNC, false
    );
    static final FunctionDescriptor PeekMessageA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PeekMessageA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "PeekMessageA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;III)I",
        constants$561.PeekMessageA$FUNC, false
    );
}


