// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1426 {

    static final FunctionDescriptor assuan_pending_line$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle assuan_pending_line$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_pending_line",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1426.assuan_pending_line$FUNC, false
    );
    static final FunctionDescriptor assuan_write_line$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle assuan_write_line$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_write_line",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1426.assuan_write_line$FUNC, false
    );
    static final FunctionDescriptor assuan_send_data$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle assuan_send_data$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_send_data",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$1426.assuan_send_data$FUNC, false
    );
    static final FunctionDescriptor assuan_sendfd$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle assuan_sendfd$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_sendfd",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1426.assuan_sendfd$FUNC, false
    );
    static final FunctionDescriptor assuan_receivefd$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle assuan_receivefd$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_receivefd",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1426.assuan_receivefd$FUNC, false
    );
    static final FunctionDescriptor assuan_set_error$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle assuan_set_error$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "assuan_set_error",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$1426.assuan_set_error$FUNC, false
    );
}


