// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$271 {

    static final MemoryLayout PPM_IDLESTATE_CHANGE_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_IDLESTATE_CHANGE_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_IDLESTATE_CHANGE_GUID", constants$271.PPM_IDLESTATE_CHANGE_GUID$LAYOUT);
    static final MemoryLayout PPM_PERFSTATES_DATA_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_PERFSTATES_DATA_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_PERFSTATES_DATA_GUID", constants$271.PPM_PERFSTATES_DATA_GUID$LAYOUT);
    static final MemoryLayout PPM_IDLESTATES_DATA_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_IDLESTATES_DATA_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_IDLESTATES_DATA_GUID", constants$271.PPM_IDLESTATES_DATA_GUID$LAYOUT);
    static final MemoryLayout PPM_IDLE_ACCOUNTING_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_IDLE_ACCOUNTING_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_IDLE_ACCOUNTING_GUID", constants$271.PPM_IDLE_ACCOUNTING_GUID$LAYOUT);
    static final MemoryLayout PPM_IDLE_ACCOUNTING_EX_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_IDLE_ACCOUNTING_EX_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_IDLE_ACCOUNTING_EX_GUID", constants$271.PPM_IDLE_ACCOUNTING_EX_GUID$LAYOUT);
    static final MemoryLayout PPM_THERMALCONSTRAINT_GUID$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("Data1"),
        C_SHORT.withName("Data2"),
        C_SHORT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, C_CHAR).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment PPM_THERMALCONSTRAINT_GUID$SEGMENT = RuntimeHelper.lookupGlobalVariable(assuan_h.LIBRARIES, "PPM_THERMALCONSTRAINT_GUID", constants$271.PPM_THERMALCONSTRAINT_GUID$LAYOUT);
}


