// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1400 {

    static final FunctionDescriptor gpgrt_printf_unlocked$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle gpgrt_printf_unlocked$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_printf_unlocked",
        "(Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1400.gpgrt_printf_unlocked$FUNC, true
    );
    static final FunctionDescriptor gpgrt_vfprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_vfprintf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_vfprintf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1400.gpgrt_vfprintf$FUNC, false
    );
    static final FunctionDescriptor gpgrt_vfprintf_unlocked$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_vfprintf_unlocked$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_vfprintf_unlocked",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1400.gpgrt_vfprintf_unlocked$FUNC, false
    );
    static final FunctionDescriptor gpgrt_setvbuf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_LONG_LONG
    );
    static final MethodHandle gpgrt_setvbuf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_setvbuf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$1400.gpgrt_setvbuf$FUNC, false
    );
    static final FunctionDescriptor gpgrt_setbuf$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_setbuf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_setbuf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1400.gpgrt_setbuf$FUNC, false
    );
    static final FunctionDescriptor gpgrt_set_binary$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle gpgrt_set_binary$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_set_binary",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1400.gpgrt_set_binary$FUNC, false
    );
}


