// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$235 {

    static final FunctionDescriptor _mm_set_epi64x$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_set_epi64x$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set_epi64x",
        "(JJ)J",
        constants$235._mm_set_epi64x$FUNC, false
    );
    static final FunctionDescriptor _mm_set_epi64$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_set_epi64$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set_epi64",
        "(JJ)J",
        constants$235._mm_set_epi64$FUNC, false
    );
    static final FunctionDescriptor _mm_set_epi32$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle _mm_set_epi32$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set_epi32",
        "(IIII)J",
        constants$235._mm_set_epi32$FUNC, false
    );
    static final FunctionDescriptor _mm_set_epi16$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_SHORT,
        C_SHORT,
        C_SHORT,
        C_SHORT,
        C_SHORT,
        C_SHORT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle _mm_set_epi16$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set_epi16",
        "(SSSSSSSS)J",
        constants$235._mm_set_epi16$FUNC, false
    );
    static final FunctionDescriptor _mm_set_epi8$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR
    );
    static final MethodHandle _mm_set_epi8$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set_epi8",
        "(BBBBBBBBBBBBBBBB)J",
        constants$235._mm_set_epi8$FUNC, false
    );
    static final FunctionDescriptor _mm_set1_epi64x$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_set1_epi64x$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_set1_epi64x",
        "(J)J",
        constants$235._mm_set1_epi64x$FUNC, false
    );
}


