// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$868 {

    static final FunctionDescriptor CryptMsgCalculateEncodedLength$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG,
        C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle CryptMsgCalculateEncodedLength$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgCalculateEncodedLength",
        "(IIILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$868.CryptMsgCalculateEncodedLength$FUNC, false
    );
    static final FunctionDescriptor CryptMsgOpenToDecode$FUNC = FunctionDescriptor.of(C_POINTER,
        C_LONG,
        C_LONG,
        C_LONG,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle CryptMsgOpenToDecode$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgOpenToDecode",
        "(IIIJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$868.CryptMsgOpenToDecode$FUNC, false
    );
    static final FunctionDescriptor CryptMsgDuplicate$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle CryptMsgDuplicate$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgDuplicate",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$868.CryptMsgDuplicate$FUNC, false
    );
    static final FunctionDescriptor CryptMsgClose$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle CryptMsgClose$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgClose",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$868.CryptMsgClose$FUNC, false
    );
    static final FunctionDescriptor CryptMsgUpdate$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_INT
    );
    static final MethodHandle CryptMsgUpdate$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgUpdate",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$868.CryptMsgUpdate$FUNC, false
    );
    static final FunctionDescriptor CryptMsgGetParam$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle CryptMsgGetParam$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "CryptMsgGetParam",
        "(Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$868.CryptMsgGetParam$FUNC, false
    );
}


