// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$141 {

    static final FunctionDescriptor _mm_srli_pi16$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_INT
    );
    static final MethodHandle _mm_srli_pi16$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_srli_pi16",
        "(JI)J",
        constants$141._mm_srli_pi16$FUNC, false
    );
    static final FunctionDescriptor _mm_srl_pi32$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_srl_pi32$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_srl_pi32",
        "(JJ)J",
        constants$141._mm_srl_pi32$FUNC, false
    );
    static final FunctionDescriptor _mm_srli_pi32$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_INT
    );
    static final MethodHandle _mm_srli_pi32$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_srli_pi32",
        "(JI)J",
        constants$141._mm_srli_pi32$FUNC, false
    );
    static final FunctionDescriptor _mm_srl_si64$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_srl_si64$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_srl_si64",
        "(JJ)J",
        constants$141._mm_srl_si64$FUNC, false
    );
    static final FunctionDescriptor _mm_srli_si64$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_INT
    );
    static final MethodHandle _mm_srli_si64$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_srli_si64",
        "(JI)J",
        constants$141._mm_srli_si64$FUNC, false
    );
    static final FunctionDescriptor _mm_and_si64$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle _mm_and_si64$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_mm_and_si64",
        "(JJ)J",
        constants$141._mm_and_si64$FUNC, false
    );
}


