// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$731 {

    static final FunctionDescriptor PFNPROCESSPOLICIESA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle PFNPROCESSPOLICIESA$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$731.PFNPROCESSPOLICIESA$FUNC, false
    );
    static final FunctionDescriptor PFNPROCESSPOLICIESW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle PFNPROCESSPOLICIESW$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$731.PFNPROCESSPOLICIESW$FUNC, false
    );
    static final FunctionDescriptor WNetGetLastErrorA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle WNetGetLastErrorA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "WNetGetLastErrorA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$731.WNetGetLastErrorA$FUNC, false
    );
    static final FunctionDescriptor WNetGetLastErrorW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle WNetGetLastErrorW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "WNetGetLastErrorW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$731.WNetGetLastErrorW$FUNC, false
    );
    static final FunctionDescriptor MultinetGetConnectionPerformanceA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle MultinetGetConnectionPerformanceA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "MultinetGetConnectionPerformanceA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$731.MultinetGetConnectionPerformanceA$FUNC, false
    );
}


