// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$970 {

    static final FunctionDescriptor IClassFactory_RemoteLockServer_Proxy$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_INT
    );
    static final MethodHandle IClassFactory_RemoteLockServer_Proxy$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_RemoteLockServer_Proxy",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$970.IClassFactory_RemoteLockServer_Proxy$FUNC, false
    );
    static final FunctionDescriptor IClassFactory_RemoteLockServer_Stub$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle IClassFactory_RemoteLockServer_Stub$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_RemoteLockServer_Stub",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$970.IClassFactory_RemoteLockServer_Stub$FUNC, false
    );
    static final FunctionDescriptor IClassFactory_CreateInstance_Proxy$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle IClassFactory_CreateInstance_Proxy$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_CreateInstance_Proxy",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$970.IClassFactory_CreateInstance_Proxy$FUNC, false
    );
    static final FunctionDescriptor IClassFactory_CreateInstance_Stub$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle IClassFactory_CreateInstance_Stub$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_CreateInstance_Stub",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$970.IClassFactory_CreateInstance_Stub$FUNC, false
    );
    static final FunctionDescriptor IClassFactory_LockServer_Proxy$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_INT
    );
    static final MethodHandle IClassFactory_LockServer_Proxy$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_LockServer_Proxy",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$970.IClassFactory_LockServer_Proxy$FUNC, false
    );
    static final FunctionDescriptor IClassFactory_LockServer_Stub$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_INT
    );
    static final MethodHandle IClassFactory_LockServer_Stub$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "IClassFactory_LockServer_Stub",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$970.IClassFactory_LockServer_Stub$FUNC, false
    );
}


