// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$316 {

    static final FunctionDescriptor PGET_MODULE_HANDLE_EXA$FUNC = FunctionDescriptor.of(C_INT,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle PGET_MODULE_HANDLE_EXA$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$316.PGET_MODULE_HANDLE_EXA$FUNC, false
    );
    static final FunctionDescriptor PGET_MODULE_HANDLE_EXW$FUNC = FunctionDescriptor.of(C_INT,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle PGET_MODULE_HANDLE_EXW$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$316.PGET_MODULE_HANDLE_EXW$FUNC, false
    );
    static final FunctionDescriptor EnumResourceNamesW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle EnumResourceNamesW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "EnumResourceNamesW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$316.EnumResourceNamesW$FUNC, false
    );
    static final FunctionDescriptor FindResourceW$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle FindResourceW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FindResourceW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$316.FindResourceW$FUNC, false
    );
    static final FunctionDescriptor FindResourceExW$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_SHORT
    );
    static final MethodHandle FindResourceExW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "FindResourceExW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;S)Ljdk/incubator/foreign/MemoryAddress;",
        constants$316.FindResourceExW$FUNC, false
    );
}


