// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1339 {

    static final FunctionDescriptor ImmAssociateContextEx$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle ImmAssociateContextEx$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmAssociateContextEx",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$1339.ImmAssociateContextEx$FUNC, false
    );
    static final FunctionDescriptor ImmGetCompositionStringA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle ImmGetCompositionStringA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmGetCompositionStringA",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$1339.ImmGetCompositionStringA$FUNC, false
    );
    static final FunctionDescriptor ImmGetCompositionStringW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle ImmGetCompositionStringW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmGetCompositionStringW",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$1339.ImmGetCompositionStringW$FUNC, false
    );
    static final FunctionDescriptor ImmSetCompositionStringA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle ImmSetCompositionStringA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmSetCompositionStringA",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$1339.ImmSetCompositionStringA$FUNC, false
    );
    static final FunctionDescriptor ImmSetCompositionStringW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle ImmSetCompositionStringW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmSetCompositionStringW",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$1339.ImmSetCompositionStringW$FUNC, false
    );
    static final FunctionDescriptor ImmGetCandidateListCountA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle ImmGetCandidateListCountA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "ImmGetCandidateListCountA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$1339.ImmGetCandidateListCountA$FUNC, false
    );
}


