// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$394 {

    static final FunctionDescriptor LocalLock$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle LocalLock$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalLock",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$394.LocalLock$FUNC, false
    );
    static final FunctionDescriptor LocalHandle$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle LocalHandle$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalHandle",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$394.LocalHandle$FUNC, false
    );
    static final FunctionDescriptor LocalUnlock$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle LocalUnlock$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalUnlock",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$394.LocalUnlock$FUNC, false
    );
    static final FunctionDescriptor LocalSize$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle LocalSize$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalSize",
        "(Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$394.LocalSize$FUNC, false
    );
    static final FunctionDescriptor LocalFlags$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle LocalFlags$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalFlags",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$394.LocalFlags$FUNC, false
    );
    static final FunctionDescriptor LocalShrink$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_INT
    );
    static final MethodHandle LocalShrink$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "LocalShrink",
        "(Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$394.LocalShrink$FUNC, false
    );
}


