// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$458 {

    static final FunctionDescriptor DeleteTimerQueue$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle DeleteTimerQueue$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "DeleteTimerQueue",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$458.DeleteTimerQueue$FUNC, false
    );
    static final FunctionDescriptor AddIntegrityLabelToBoundaryDescriptor$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle AddIntegrityLabelToBoundaryDescriptor$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "AddIntegrityLabelToBoundaryDescriptor",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$458.AddIntegrityLabelToBoundaryDescriptor$FUNC, false
    );
    static final FunctionDescriptor GetCurrentHwProfileA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle GetCurrentHwProfileA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "GetCurrentHwProfileA",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$458.GetCurrentHwProfileA$FUNC, false
    );
    static final FunctionDescriptor GetCurrentHwProfileW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle GetCurrentHwProfileW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "GetCurrentHwProfileW",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$458.GetCurrentHwProfileW$FUNC, false
    );
    static final FunctionDescriptor VerifyVersionInfoA$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG_LONG
    );
    static final MethodHandle VerifyVersionInfoA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VerifyVersionInfoA",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$458.VerifyVersionInfoA$FUNC, false
    );
    static final FunctionDescriptor VerifyVersionInfoW$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG_LONG
    );
    static final MethodHandle VerifyVersionInfoW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "VerifyVersionInfoW",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$458.VerifyVersionInfoW$FUNC, false
    );
}


