// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1399 {

    static final FunctionDescriptor gpgrt_read_line$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_read_line$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_read_line",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$1399.gpgrt_read_line$FUNC, false
    );
    static final FunctionDescriptor gpgrt_fprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_fprintf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_fprintf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1399.gpgrt_fprintf$FUNC, true
    );
    static final FunctionDescriptor gpgrt_fprintf_unlocked$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_fprintf_unlocked$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_fprintf_unlocked",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1399.gpgrt_fprintf_unlocked$FUNC, true
    );
    static final FunctionDescriptor gpgrt_fprintf_sf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_fprintf_sf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_fprintf_sf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1399.gpgrt_fprintf_sf$FUNC, true
    );
    static final FunctionDescriptor gpgrt_fprintf_sf_unlocked$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gpgrt_fprintf_sf_unlocked$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_fprintf_sf_unlocked",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1399.gpgrt_fprintf_sf_unlocked$FUNC, true
    );
    static final FunctionDescriptor gpgrt_printf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle gpgrt_printf$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "gpgrt_printf",
        "(Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$1399.gpgrt_printf$FUNC, true
    );
}


