// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$171 {

    static final FunctionDescriptor _putenv$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle _putenv$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_putenv",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$171._putenv$FUNC, false
    );
    static final FunctionDescriptor _wputenv$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle _wputenv$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_wputenv",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$171._wputenv$FUNC, false
    );
    static final FunctionDescriptor _fullpath$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle _fullpath$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_fullpath",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$171._fullpath$FUNC, false
    );
    static final FunctionDescriptor _ecvt$FUNC = FunctionDescriptor.of(C_POINTER,
        C_DOUBLE,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _ecvt$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_ecvt",
        "(DILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$171._ecvt$FUNC, false
    );
    static final FunctionDescriptor _fcvt$FUNC = FunctionDescriptor.of(C_POINTER,
        C_DOUBLE,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle _fcvt$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_fcvt",
        "(DILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$171._fcvt$FUNC, false
    );
    static final FunctionDescriptor _gcvt$FUNC = FunctionDescriptor.of(C_POINTER,
        C_DOUBLE,
        C_INT,
        C_POINTER
    );
    static final MethodHandle _gcvt$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "_gcvt",
        "(DILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$171._gcvt$FUNC, false
    );
}


