// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$710 {

    static final FunctionDescriptor RegDeleteKeyA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RegDeleteKeyA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegDeleteKeyA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$710.RegDeleteKeyA$FUNC, false
    );
    static final FunctionDescriptor RegDeleteKeyW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle RegDeleteKeyW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegDeleteKeyW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$710.RegDeleteKeyW$FUNC, false
    );
    static final FunctionDescriptor RegDeleteKeyExA$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle RegDeleteKeyExA$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegDeleteKeyExA",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$710.RegDeleteKeyExA$FUNC, false
    );
    static final FunctionDescriptor RegDeleteKeyExW$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle RegDeleteKeyExW$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegDeleteKeyExW",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$710.RegDeleteKeyExW$FUNC, false
    );
    static final FunctionDescriptor RegDisableReflectionKey$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle RegDisableReflectionKey$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegDisableReflectionKey",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$710.RegDisableReflectionKey$FUNC, false
    );
    static final FunctionDescriptor RegEnableReflectionKey$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle RegEnableReflectionKey$MH = RuntimeHelper.downcallHandle(
        assuan_h.LIBRARIES, "RegEnableReflectionKey",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$710.RegEnableReflectionKey$FUNC, false
    );
}


