// Generated by jextract

package de.itemis.mosig.jassuan;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1494 {

    static final MemorySegment NCRYPT_CERTIFICATE_PROPERTY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
    static final MemorySegment NCRYPT_PIN_PROMPT_PROPERTY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
    static final MemorySegment NCRYPT_USER_CERTSTORE_PROPERTY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
    static final MemorySegment NCRYPT_ROOT_CERTSTORE_PROPERTY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
    static final MemorySegment NCRYPT_SECURE_PIN_PROPERTY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
    static final MemorySegment NCRYPT_ASSOCIATED_ECDH_KEY$SEGMENT = CLinker.toCString("S", ResourceScope.newImplicitScope());
}


